---
- name: config | jenkins job
  jenkins_job:
    config: "{{lookup('template', 'templates/job.xml.j2')}}"
    name: "{{jenkins_job_name}}"
    url: "{{jenkins_url}}"
    user: "{{jenkins_admin_name}}"
    password: "{{jenkins_admin_password}}"
